Upgrade nydus to 0.11.0
In sentry 7.5.4, there is a redis `ZADD` usage in worker: https://github.com/getsentry/sentry/blob/7.5.4/src/sentry/buffer/redis.py#L86.

That may break the worker because `ZADD` have two different arguments order in redis-py:

- `(name, key, score)` in [legacy client](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2009)
- `(name, score, key)` in [strict client](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L1568)

The nydus 0.10 is using `strict=False` in redis by default. It will cause the worker of sentry 7.5.4 throw exceptions:

```
Error processing '_save_aggregate' on 'EventManager': Command # 7 (ZADD b:p b:k:sentry.group:f3bf07751cf4ad117b31e6c8817e73bf 1435235043.64) of pipeline caused error: value is not a valid float
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 473, in _save_aggregate
    is_regression = self._process_existing_aggregate(group, event, kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/event_manager.py", line 536, in _process_existing_aggregate
    }, extra)
  File "/usr/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 87, in incr
    pipe.execute()
  File "/usr/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 2492, in _execute_transaction
    self.raise_first_error(commands, response)
  File "/usr/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 2526, in raise_first_error
    raise r
ResponseError: Command # 7 (ZADD b:p b:k:sentry.group:f3bf07751cf4ad117b31e6c8817e73bf 1435235043.64) of pipeline caused error: value is not a valid float
```

So upgrading the nydus will enable strict mode of redis client and resolve this issue.